<?php

namespace AppBundle\Repository;

/**
 * RAVITALLEMENTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RAVITALLEMENTRepository extends \Doctrine\ORM\EntityRepository
{
}
