<?php

namespace AppBundle\Repository;

/**
 * StatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class StatistiqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStat($debut,$fin)
    {
        $query="
        SELECT s
        FROM AppBundle:Statistique s
        WHERE s.date BETWEEN '$debut' and '$fin'";

        return $this->getEntityManager()->createQuery($query)->getResult();
    }

    
}
